#!/bin/bash
#
# Created By: Gabriel Gonzalez (contact me at gabeg@bu.edu)
# 
# Purpose: Changes the paths in the source files to avoid path errors.
#

## Fix paths in the configuration files
echo "Modifying the file paths for '$USER'..."
sed -i "s/\/mnt\/Linux\/Share/\/home\/$USER/g" \
    "$HOME"/scripts/programs/weather/src/wuapi.py
